### ISSUE TITLE
Road map

### ISSUE THREAD

**Issue by isfttr** [isfttr/RPIpy#3]
Adicionar no readme
 
- [ ]  Feature: Gerar relatório semanal v0.2
- [ ]  Feature: Gerar uma base de dados v0.3
- [ ]  Feature: Enviar e-mails com relatório v0.4
- [ ]  Release v1.0-alpha: 1 usuário
- [ ]  Correção de bugs
- [ ]  Expansão de acesso a RPIs mais antigas
- [ ]  Release v1.0-beta: até 5 usuários
- [ ]  Correção de bugs
- [ ]  Release v1.0: CITT
- [ ]  Mais funcionalidades
